# Generated by Django 3.0.6 on 2020-05-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityperiod',
            name='ids',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='activityperiod',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
